### ISSUE TITLE
Add simulation for fairness KPI

### ISSUE THREAD

**Issue by abedaeed17** [muhammadeid172/QUIC-vs-TCP-A-Performance-Evaluation-over-LTE-with-NS-3#19]

**Comment by muhammadeid172** [comment]
Final status:
- Managed to implement ns-3 comparison in two cases, 1 Quic vs 2 TCP, and 1 Quic vs 5 TCP.
- Failed to implement inter-Quic comparison: The reason could be that the Quic module does not support two connections to the same receiver, we opened an issue in the Quic module repo and waiting for confirmation (https://github.com/signetlabdei/quic-ns-3/issues/46).
Because of that we were inable to implement the Quic vs Quic and 2 Quic vs 2 TCP scenarios.
